spring:
  application:
    name: observability
  datasource:
    url: jdbc:h2:mem:products-db
  h2:
    console:
      enabled: true
  docker:
    compose:
      enabled: false

server:
  port: 8085
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  endpoint:
    health:
      show:
        details: always

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  endpoints:
    web:
      exposure:
        include: "*"
    metrics:
      tags:
        application: ${spring.application.name}  # Ajout de tags globaux
      enable:
        jvm: true                # Activer les métriques JVM
        http:
          server:
            requests: true        # Activer les métriques des requêtes HTTP
        logback: true             # Activer les métriques de Logback
        uptime: true              # Activer les métriques d'uptime
        process: true             # Activer les métriques de processus
