global:
  scrape_interval: 10s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
     - targets: [ 'localhost:9090' ]
  - job_name: 'product_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.43.247:8085']
        labels:
          application: 'Product Service application'



